name: CUDA
on:
  workflow_dispatch: null
  push:
    paths: ['cuda/*']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    # For biggish images, github actions runs out of disk space.
      - name: cleanup disk space
        run: sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build the Docker image (torch)
        run: docker build cuda --build-arg BASE=quay.io/jupyter/pytorch-notebook:cuda12-ubuntu-24.04 --tag ghcr.io/schmidtdse/cuda:latest
      - name: Publish cuda (torch)
        run: docker push ghcr.io/schmidtdse/cuda:latest
      
      - name: Build the Docker image (tensorflow)
        run: docker build cuda --build-arg BASE=quay.io/jupyter/tensorflow-notebook:cuda-latest --tag ghcr.io/schmidtdse/tensorflow:latest
      - name: Publish tensorflow
        run: docker push ghcr.io/schmidtdse/tensorflow:latest

