name: soundhub
on:
  workflow_dispatch: null
  push:
    paths: ['soundhub/*']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    # For biggish images, github actions runs out of disk space.
      - name: cleanup disk space
        run: sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc

      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build the Docker image (cpu)
        run: docker buildx build soundhub --build-arg BASE=ghcr.io/schmidtdse/base --tag ghcr.io/schmidtdse/soundhub-cpu:latest
      - name: Publish
        run: docker push ghcr.io/schmidtdse/soundhub-cpu:latest

      - name: Build the Docker image (torch)
        run: docker buildx build soundhub --build-arg BASE=ghcr.io/schmidtdse/cuda --tag ghcr.io/schmidtdse/soundhub-torch:latest
      - name: Publish
        run: docker push ghcr.io/schmidtdse/soundhub-torch:latest

      - name: purge space
        run: docker rmi -f $(docker images -q)

      - name: Build the Docker image (tensorflow)
        run: docker buildx build soundhub --build-arg BASE=ghcr.io/schmidtdse/tensorflow --tag ghcr.io/schmidtdse/soundhub-tensorflow:latest
      - name: Publish
        run: push ghcr.io/schmidtdse/soundhub-tensorflow:latest

